# Evaluate method_a predictor accuracy

Loads an `eval__baseline__qh_predictions__{MODEL_DATA}.json` file (produced by
`create_verification_data`, run once per (TASK, MODEL_DATA)), then runs each
trained `method_a_predictors` model (one per MODEL_TRAIN) on those same
prompts, extracts the predicted binary label from `<answer>X</answer>`, and
compares against the ground-truth `label` field to compute accuracy.

Only one vllm model is ever loaded at a time (freed before the next model
loads). Eval records for a given (TASK, MODEL_DATA) are loaded once and
reused across every MODEL_TRAIN.

Run this notebook from the repo root (`abstention-reasoning/`).

In [24]:
import os

# Restrict to a single GPU before vllm/torch are imported anywhere in this
# process. Set to the device you want to use, or comment out to use whatever
# CUDA_VISIBLE_DEVICES is already set in the shell that launched Jupyter.
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "1")

import re
import gc
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "pipeline").exists():
    # Allow running the notebook from a subdirectory too.
    REPO_ROOT = Path(__file__).resolve().parent if "__file__" in dir() else REPO_ROOT
sys.path.insert(0, str(REPO_ROOT))

from pipeline.core.io import load_json
from pipeline.core.generator import Generator, GenerationConfig

In [25]:
# === Config ===

# Sweep over every (task, model_data, model_train) combination. Adjust freely,
# or shrink these lists to evaluate a single combo.
TASKS = ["countdown", "competition_math"]
MODEL_DATA_LIST = ["qwen2.5-3b", "qwen3-4b-base"]
MODEL_TRAIN_LIST = ["qwen2.5-3b", "qwen2.5-1.5b"]

EVAL_FILE_TEMPLATE = "artifacts/{task}/sft_datasets_verification/eval__baseline__qh_predictions__{model_data}.json"
MODEL_PATH_TEMPLATE = "artifacts/{task}/models/method_a_predictors/{model_data}/{model_train}/model"

# Greedy decoding: this is a binary classification task, not open-ended
# generation, so temperature=0 gives the model's actual argmax prediction
# rather than a sampled one.
TEMPERATURE = 0.0
TOP_P = 1.0
MAX_NEW_TOKENS = 16  # only need "<answer>0</answer>" or "<answer>1</answer>"
TENSOR_PARALLEL_SIZE = 1
GPU_MEMORY_UTILIZATION = 0.9

ANSWER_RE = re.compile(r"<answer>\s*([01])\s*</answer>")

In [26]:
def extract_predicted_label(text: str) -> int | None:
    """Parse the predicted 0/1 label out of a generated completion.

    Returns None if the model didn't emit a well-formed <answer> tag (counted
    as a wrong prediction, not silently dropped, when computing accuracy).
    """
    match = ANSWER_RE.search(text)
    if match is None:
        return None
    return int(match.group(1))


def run_predictor(model_path: str, records: list[dict]) -> list[int | None]:
    """Load one predictor model, run it over eval records, then free it.

    Only one vllm engine is ever alive at a time: the previous model (if any)
    must already be freed by the caller before this is invoked.
    """
    config = GenerationConfig(
        model_name=model_path,
        temperature=TEMPERATURE,
        top_p=TOP_P,
        max_new_tokens=MAX_NEW_TOKENS,
        num_samples=1,
        tensor_parallel_size=TENSOR_PARALLEL_SIZE,
        gpu_memory_utilization=GPU_MEMORY_UTILIZATION,
        seed=42,
    )
    generator = Generator(config)
    prompts = [r["prompt"] for r in records]
    outputs = generator.generate(prompts)  # list[list[{"text": ...}]], one sample each

    predictions = [extract_predicted_label(samples[0]["text"]) for samples in outputs]

    # Explicitly release the vllm engine before the next model loads --
    # otherwise GPU memory from consecutive models in the sweep accumulates.
    del generator
    gc.collect()
    try:
        import torch
        torch.cuda.empty_cache()
    except ImportError:
        pass

    return predictions


def compute_metrics(records: list[dict], predictions: list[int | None]) -> dict:
    """Accuracy/precision/recall/F1 + parse-failure rate for one eval run."""
    labels = [r["label"] for r in records]

    tp = fp = tn = fn = parse_failures = 0
    for label, pred in zip(labels, predictions):
        if pred is None:
            parse_failures += 1
            continue  # counted as wrong below via correct-count math
        if pred == 1 and label == 1:
            tp += 1
        elif pred == 1 and label == 0:
            fp += 1
        elif pred == 0 and label == 0:
            tn += 1
        elif pred == 0 and label == 1:
            fn += 1

    n = len(records)
    correct = tp + tn
    accuracy = correct / n if n else float("nan")
    precision = tp / (tp + fp) if (tp + fp) else float("nan")
    recall = tp / (tp + fn) if (tp + fn) else float("nan")
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else float("nan")
    )

    return {
        "n": n,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tp": tp,
        "fp": fp,
        "tn": tn,
        "fn": fn,
        "parse_failures": parse_failures,
    }

In [27]:
# === Sweep ===
# Eval records are loaded once per (task, model_data) and reused across every
# model_train. Exactly one vllm model is loaded at a time.

results = []
eval_records_cache: dict[tuple[str, str], list[dict]] = {}
# Keyed by (task, model_data, model_train) -> {"records": ..., "predictions": ...}.
# Kept around so a later cell can break accuracy down by difficulty without
# re-running generation.
detailed_results: dict[tuple[str, str, str], dict] = {}

for task in TASKS:
    for model_data in MODEL_DATA_LIST:
        eval_path = REPO_ROOT / EVAL_FILE_TEMPLATE.format(task=task, model_data=model_data)
        if not eval_path.exists():
            print(f"SKIP (missing eval file): {eval_path}")
            continue
        cache_key = (task, model_data)
        if cache_key not in eval_records_cache:
            eval_records_cache[cache_key] = load_json(eval_path)
        records = eval_records_cache[cache_key]

        for model_train in MODEL_TRAIN_LIST:
            model_path = REPO_ROOT / MODEL_PATH_TEMPLATE.format(
                task=task, model_data=model_data, model_train=model_train
            )
            if not model_path.exists():
                print(f"SKIP (missing model): {model_path}")
                continue

            print(f"=== task={task} model_data={model_data} model_train={model_train} ===")
            predictions = run_predictor(str(model_path), records)
            metrics = compute_metrics(records, predictions)
            metrics.update(task=task, model_data=model_data, model_train=model_train)
            results.append(metrics)
            detailed_results[(task, model_data, model_train)] = {
                "records": records,
                "predictions": predictions,
            }
            print(metrics)

summary = pd.DataFrame(results)
cols = ["task", "model_data", "model_train", "n", "accuracy", "precision", "recall", "f1", "parse_failures"]
summary = summary[cols] if not summary.empty else summary
summary

=== task=countdown model_data=qwen2.5-3b model_train=qwen2.5-3b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model
INFO 09-30 10:53:18 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model'}
INFO 09-30 10:53:18 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:53:18 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:53:18 [model.py:1561] Using max model len 32768
INFO 09-30 10:53:18 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:18 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:18 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:46683 backend=nccl
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:18 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:19 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model...
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:20 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:01,  1.52it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.22it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.42it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.39it/s]
(EngineCore_DP0 pid=1009195)

(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:22 [default_loader.py:291] Loading weights took 2.29 seconds
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:23 [gpu_model_runner.py:4118] Model loading took 5.79 GiB memory and 3.042315 seconds
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:29 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/3c242bd28a/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:29 [backends.py:865] Dynamo bytecode transform time: 5.78 s
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:34 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.437 s
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:34 [monitor.py:34] torch.compile takes 7.22 s in total
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:35 [gpu_worker.py:356] Available KV cache memory: 32.73 GiB
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:35 [kv_cache_utils.py:1307] GPU KV cache size: 953,376 tokens
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:35 [kv_cache_utils.py:1312] Maximum concurrency for 32,768 tokens per request: 29.09x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 21.64it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 24.70it/s]

(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:40 [gpu_model_runner.py:5051] Graph capturing finished in 5 secs, took 0.53 GiB
(EngineCore_DP0 pid=1009195) INFO 09-30 10:53:40 [core.py:272] init engine (profile, create kv cache, warmup model) took 16.58 seconds

(EngineCore_DP0 pid=1009195) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:53:41 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1500/1500 [00:01<00:00, 1488.97it/s]
Processed prompts: 100%|██████████| 1500/1500 [00:13<00:00, 114.19it/s, est. speed input: 23665.89 toks/s, output: 799.38 toks/s]

{'n': 1500, 'accuracy': 0.758, 'precision': 0.758, 'recall': 1.0, 'f1': 0.8623435722411832, 'tp': 1137, 'fp': 363, 'tn': 0, 'fn': 0, 'parse_failures': 0, 'task': 'countdown', 'model_data': 'qwen2.5-3b', 'model_train': 'qwen2.5-3b'}
=== task=countdown model_data=qwen2.5-3b model_train=qwen2.5-1.5b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model
INFO 09-30 10:53:56 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model'}
INFO 09-30 10:53:56 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:53:56 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:53:56 [model.py:1561] Using max model len 131072
INFO 09-30 10:53:56 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:56 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:57 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:34949 backend=nccl
(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:57 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:58 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model...
(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:58 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  2.20it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.62it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.54it/s]
(EngineCore_DP0 pid=1009968)

(EngineCore_DP0 pid=1009968) INFO 09-30 10:53:59 [default_loader.py:291] Loading weights took 0.85 seconds
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:00 [gpu_model_runner.py:4118] Model loading took 2.91 GiB memory and 1.568506 seconds
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:05 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/f5206cd8d8/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:05 [backends.py:865] Dynamo bytecode transform time: 4.70 s
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:09 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 0.835 s
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:09 [monitor.py:34] torch.compile takes 5.54 s in total
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:10 [gpu_worker.py:356] Available KV cache memory: 35.62 GiB
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:10 [kv_cache_utils.py:1307] GPU KV cache size: 1,333,952 tokens
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:10 [kv_cache_utils.py:1312] Maximum concurrency for 131,072 tokens per request: 10.18x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 29.71it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 32.10it/s]

(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:13 [gpu_model_runner.py:5051] Graph capturing finished in 4 secs, took 0.45 GiB
(EngineCore_DP0 pid=1009968) INFO 09-30 10:54:13 [core.py:272] init engine (profile, create kv cache, warmup model) took 13.27 seconds

(EngineCore_DP0 pid=1009968) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:54:15 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1500/1500 [00:01<00:00, 1494.62it/s]
Processed prompts: 100%|██████████| 1500/1500 [00:06<00:00, 235.98it/s, est. speed input: 48911.31 toks/s, output: 1652.12 toks/s]

{'n': 1500, 'accuracy': 0.7606666666666667, 'precision': 0.7603748326639893, 'recall': 0.9991204925241864, 'f1': 0.8635499809958191, 'tp': 1136, 'fp': 358, 'tn': 5, 'fn': 1, 'parse_failures': 0, 'task': 'countdown', 'model_data': 'qwen2.5-3b', 'model_train': 'qwen2.5-1.5b'}
=== task=countdown model_data=qwen3-4b-base model_train=qwen2.5-3b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model
INFO 09-30 10:54:23 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model'}
INFO 09-30 10:54:23 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:54:23 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:54:23 [model.py:1561] Using max model len 32768
INFO 09-30 10:54:23 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:23 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:24 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:38987 backend=nccl
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:24 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:24 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model...
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:25 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:01,  1.45it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.14it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.32it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.29it/s]
(EngineCore_DP0 pid=1010411)

(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:28 [default_loader.py:291] Loading weights took 2.45 seconds
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:29 [gpu_model_runner.py:4118] Model loading took 5.79 GiB memory and 3.216536 seconds
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:35 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/cf34b92c83/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:35 [backends.py:865] Dynamo bytecode transform time: 5.73 s
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:40 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.473 s
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:40 [monitor.py:34] torch.compile takes 7.21 s in total
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:41 [gpu_worker.py:356] Available KV cache memory: 32.73 GiB
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:41 [kv_cache_utils.py:1307] GPU KV cache size: 953,376 tokens
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:41 [kv_cache_utils.py:1312] Maximum concurrency for 32,768 tokens per request: 29.09x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 21.63it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 24.78it/s]

(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:45 [gpu_model_runner.py:5051] Graph capturing finished in 5 secs, took 0.53 GiB
(EngineCore_DP0 pid=1010411) INFO 09-30 10:54:45 [core.py:272] init engine (profile, create kv cache, warmup model) took 16.64 seconds

(EngineCore_DP0 pid=1010411) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:54:47 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1500/1500 [00:01<00:00, 1482.00it/s]
Processed prompts: 100%|██████████| 1500/1500 [00:13<00:00, 112.47it/s, est. speed input: 23309.23 toks/s, output: 787.34 toks/s]

{'n': 1500, 'accuracy': 0.8113333333333334, 'precision': 0.8403722261989979, 'recall': 0.9513776337115073, 'f1': 0.8924363359939186, 'tp': 1174, 'fp': 223, 'tn': 43, 'fn': 60, 'parse_failures': 0, 'task': 'countdown', 'model_data': 'qwen3-4b-base', 'model_train': 'qwen2.5-3b'}
=== task=countdown model_data=qwen3-4b-base model_train=qwen2.5-1.5b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model
INFO 09-30 10:55:02 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model'}
INFO 09-30 10:55:02 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:55:02 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:55:02 [model.py:1561] Using max model len 131072
INFO 09-30 10:55:02 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:02 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:02 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:58575 backend=nccl
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:03 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:03 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model...
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:04 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  2.26it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.65it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.57it/s]
(EngineCore_DP0 pid=1010809)

(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:05 [default_loader.py:291] Loading weights took 0.84 seconds
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:06 [gpu_model_runner.py:4118] Model loading took 2.91 GiB memory and 1.575065 seconds
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:11 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/be0cb54c8c/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:11 [backends.py:865] Dynamo bytecode transform time: 4.68 s
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:14 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 0.836 s
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:14 [monitor.py:34] torch.compile takes 5.52 s in total
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:15 [gpu_worker.py:356] Available KV cache memory: 35.62 GiB
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:15 [kv_cache_utils.py:1307] GPU KV cache size: 1,333,952 tokens
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:15 [kv_cache_utils.py:1312] Maximum concurrency for 131,072 tokens per request: 10.18x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 29.53it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 32.24it/s]

(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:19 [gpu_model_runner.py:5051] Graph capturing finished in 4 secs, took 0.45 GiB
(EngineCore_DP0 pid=1010809) INFO 09-30 10:55:19 [core.py:272] init engine (profile, create kv cache, warmup model) took 13.28 seconds

(EngineCore_DP0 pid=1010809) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/countdown/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:55:20 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1500/1500 [00:01<00:00, 1484.07it/s]
Processed prompts: 100%|██████████| 1500/1500 [00:06<00:00, 235.74it/s, est. speed input: 48859.87 toks/s, output: 1650.38 toks/s]

{'n': 1500, 'accuracy': 0.8186666666666667, 'precision': 0.8411347517730496, 'recall': 0.9611021069692058, 'f1': 0.897125567322239, 'tp': 1186, 'fp': 224, 'tn': 42, 'fn': 48, 'parse_failures': 0, 'task': 'countdown', 'model_data': 'qwen3-4b-base', 'model_train': 'qwen2.5-1.5b'}
=== task=competition_math model_data=qwen2.5-3b model_train=qwen2.5-3b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model
INFO 09-30 10:55:29 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model'}
INFO 09-30 10:55:29 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:55:29 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:55:29 [model.py:1561] Using max model len 32768
INFO 09-30 10:55:29 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:29 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:30 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:44629 backend=nccl
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:30 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:30 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model...
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:31 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:01,  1.42it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.17it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.35it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.32it/s]
(EngineCore_DP0 pid=1011139)

(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:34 [default_loader.py:291] Loading weights took 2.39 seconds
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:35 [gpu_model_runner.py:4118] Model loading took 5.79 GiB memory and 3.159818 seconds
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:41 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/faf69e999f/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:41 [backends.py:865] Dynamo bytecode transform time: 5.72 s
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:45 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.469 s
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:45 [monitor.py:34] torch.compile takes 7.19 s in total
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:46 [gpu_worker.py:356] Available KV cache memory: 32.73 GiB
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:46 [kv_cache_utils.py:1307] GPU KV cache size: 953,376 tokens
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:46 [kv_cache_utils.py:1312] Maximum concurrency for 32,768 tokens per request: 29.09x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 21.66it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 24.82it/s]

(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:51 [gpu_model_runner.py:5051] Graph capturing finished in 5 secs, took 0.53 GiB
(EngineCore_DP0 pid=1011139) INFO 09-30 10:55:51 [core.py:272] init engine (profile, create kv cache, warmup model) took 16.60 seconds

(EngineCore_DP0 pid=1011139) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-3b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:55:52 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1764/1764 [00:01<00:00, 1402.82it/s]
Processed prompts: 100%|██████████| 1764/1764 [00:19<00:00, 90.83it/s, est. speed input: 21405.55 toks/s, output: 635.83 toks/s]

{'n': 1764, 'accuracy': 0.7171201814058957, 'precision': 0.7637867647058824, 'recall': 0.7744641192917054, 'f1': 0.7690883850069413, 'tp': 831, 'fp': 257, 'tn': 434, 'fn': 242, 'parse_failures': 0, 'task': 'competition_math', 'model_data': 'qwen2.5-3b', 'model_train': 'qwen2.5-3b'}
=== task=competition_math model_data=qwen2.5-3b model_train=qwen2.5-1.5b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model
INFO 09-30 10:56:14 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model'}
INFO 09-30 10:56:14 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:56:14 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:56:14 [model.py:1561] Using max model len 131072
INFO 09-30 10:56:14 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:14 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:15 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:42137 backend=nccl
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:15 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:16 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model...
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:16 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  2.18it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.57it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.50it/s]
(EngineCore_DP0 pid=1011471)

(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:17 [default_loader.py:291] Loading weights took 0.87 seconds
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:18 [gpu_model_runner.py:4118] Model loading took 2.91 GiB memory and 1.585812 seconds
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:23 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/0a26d91a7c/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:23 [backends.py:865] Dynamo bytecode transform time: 4.67 s
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:27 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 0.836 s
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:27 [monitor.py:34] torch.compile takes 5.50 s in total
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:28 [gpu_worker.py:356] Available KV cache memory: 35.62 GiB
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:28 [kv_cache_utils.py:1307] GPU KV cache size: 1,333,952 tokens
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:28 [kv_cache_utils.py:1312] Maximum concurrency for 131,072 tokens per request: 10.18x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 29.69it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 32.15it/s]

(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:31 [gpu_model_runner.py:5051] Graph capturing finished in 4 secs, took 0.45 GiB
(EngineCore_DP0 pid=1011471) INFO 09-30 10:56:31 [core.py:272] init engine (profile, create kv cache, warmup model) took 13.28 seconds

(EngineCore_DP0 pid=1011471) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen2.5-3b/qwen2.5-1.5b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:56:33 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1764/1764 [00:01<00:00, 1399.55it/s]
Processed prompts: 100%|██████████| 1764/1764 [00:09<00:00, 189.72it/s, est. speed input: 44713.46 toks/s, output: 1328.17 toks/s]

{'n': 1764, 'accuracy': 0.7409297052154195, 'precision': 0.7528735632183908, 'recall': 0.8546132339235788, 'f1': 0.8005237887385422, 'tp': 917, 'fp': 301, 'tn': 390, 'fn': 156, 'parse_failures': 0, 'task': 'competition_math', 'model_data': 'qwen2.5-3b', 'model_train': 'qwen2.5-1.5b'}
=== task=competition_math model_data=qwen3-4b-base model_train=qwen2.5-3b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model
INFO 09-30 10:56:44 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model'}
INFO 09-30 10:56:44 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:56:44 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:56:44 [model.py:1561] Using max model len 32768
INFO 09-30 10:56:44 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:44 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:45 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:51583 backend=nccl
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:45 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:46 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model...
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:47 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:01,  1.49it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.21it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.37it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.35it/s]
(EngineCore_DP0 pid=1011786)

(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:49 [default_loader.py:291] Loading weights took 2.34 seconds
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:50 [gpu_model_runner.py:4118] Model loading took 5.79 GiB memory and 3.122105 seconds
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:56 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/e26075cb1e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1011786) INFO 09-30 10:56:56 [backends.py:865] Dynamo bytecode transform time: 5.74 s
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:01 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.457 s
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:01 [monitor.py:34] torch.compile takes 7.20 s in total
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:02 [gpu_worker.py:356] Available KV cache memory: 32.73 GiB
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:02 [kv_cache_utils.py:1307] GPU KV cache size: 953,376 tokens
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:02 [kv_cache_utils.py:1312] Maximum concurrency for 32,768 tokens per request: 29.09x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:02<00:00, 21.59it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 24.70it/s]

(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:07 [gpu_model_runner.py:5051] Graph capturing finished in 5 secs, took 0.53 GiB
(EngineCore_DP0 pid=1011786) INFO 09-30 10:57:07 [core.py:272] init engine (profile, create kv cache, warmup model) took 16.63 seconds

(EngineCore_DP0 pid=1011786) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-3b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:57:08 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1764/1764 [00:01<00:00, 1395.96it/s]
Processed prompts: 100%|██████████| 1764/1764 [00:19<00:00, 90.70it/s, est. speed input: 21375.84 toks/s, output: 634.95 toks/s]

{'n': 1764, 'accuracy': 0.8112244897959183, 'precision': 0.8325762491888384, 'recall': 0.9447717231222386, 'f1': 0.8851328044153156, 'tp': 1283, 'fp': 258, 'tn': 148, 'fn': 75, 'parse_failures': 0, 'task': 'competition_math', 'model_data': 'qwen3-4b-base', 'model_train': 'qwen2.5-3b'}
=== task=competition_math model_data=qwen3-4b-base model_train=qwen2.5-1.5b ===
Loading model: /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model
INFO 09-30 10:57:29 [utils.py:261] non-default args: {'disable_log_stats': True, 'model': '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model'}
INFO 09-30 10:57:30 [model.py:541] Resolved architecture: Qwen2ForCausalLM
INFO 09-30 10:57:30 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 09-30 10:57:30 [model.py:1561] Using max model len 131072
INFO 09-30 10:57:30 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:30 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model', speculative_config=None, tokenizer='/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:30 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.209.224.73:35729 backend=nccl
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:30 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:31 [gpu_model_runner.py:4021] Starting to load model /home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model...
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:32 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  2.06it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.44it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.36it/s]
(EngineCore_DP0 pid=1012409)

(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:33 [default_loader.py:291] Loading weights took 0.91 seconds
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:34 [gpu_model_runner.py:4118] Model loading took 2.91 GiB memory and 1.631555 seconds
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:39 [backends.py:805] Using cache directory: /home/tanyagoyal/.cache/vllm/torch_compile_cache/2251615d8e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:39 [backends.py:865] Dynamo bytecode transform time: 4.66 s
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:42 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 0.831 s
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:42 [monitor.py:34] torch.compile takes 5.49 s in total
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:43 [gpu_worker.py:356] Available KV cache memory: 35.62 GiB
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:43 [kv_cache_utils.py:1307] GPU KV cache size: 1,333,952 tokens
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:43 [kv_cache_utils.py:1312] Maximum concurrency for 131,072 tokens per request: 10.18x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:01<00:00, 29.70it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:01<00:00, 32.05it/s]

(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:47 [gpu_model_runner.py:5051] Graph capturing finished in 4 secs, took 0.45 GiB
(EngineCore_DP0 pid=1012409) INFO 09-30 10:57:47 [core.py:272] init engine (profile, create kv cache, warmup model) took 13.16 seconds

(EngineCore_DP0 pid=1012409) The tokenizer you are loading from '/home/tanyagoyal/abstention-reasoning/artifacts/competition_math/models/method_a_predictors/qwen3-4b-base/qwen2.5-1.5b/model' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

INFO 09-30 10:57:48 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 1764/1764 [00:01<00:00, 1404.31it/s]
Processed prompts: 100%|██████████| 1764/1764 [00:09<00:00, 189.47it/s, est. speed input: 44654.82 toks/s, output: 1326.42 toks/s]

{'n': 1764, 'accuracy': 0.8010204081632653, 'precision': 0.834107498341075, 'recall': 0.9256259204712813, 'f1': 0.8774869109947645, 'tp': 1257, 'fp': 250, 'tn': 156, 'fn': 101, 'parse_failures': 0, 'task': 'competition_math', 'model_data': 'qwen3-4b-base', 'model_train': 'qwen2.5-1.5b'}

,task,model_data,model_train,n,accuracy,precision,recall,f1,parse_failures
0,countdown,qwen2.5-3b,qwen2.5-3b,1500,0.758000,0.758000,1.000000,0.862344,0
1,countdown,qwen2.5-3b,qwen2.5-1.5b,1500,0.760667,0.760375,0.999120,0.863550,0
2,countdown,qwen3-4b-base,qwen2.5-3b,1500,0.811333,0.840372,0.951378,0.892436,0
3,countdown,qwen3-4b-base,qwen2.5-1.5b,1500,0.818667,0.841135,0.961102,0.897126,0
4,competition_math,qwen2.5-3b,qwen2.5-3b,1764,0.717120,0.763787,0.774464,0.769088,0
5,competition_math,qwen2.5-3b,qwen2.5-1.5b,1764,0.740930,0.752874,0.854613,0.800524,0
6,competition_math,qwen3-4b-base,qwen2.5-3b,1764,0.811224,0.832576,0.944772,0.885133,0
7,competition_math,qwen3-4b-base,qwen2.5-1.5b,1764,0.801020,0.834107,0.925626,0.877487,0

## Optional: save summary to disk

In [28]:
OUTPUT_CSV = REPO_ROOT / "artifacts" / "method_a_predictor_eval_summary.csv"
OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True)
summary.to_csv(OUTPUT_CSV, index=False)
print(f"Saved summary to {OUTPUT_CSV}")

Saved summary to /home/tanyagoyal/abstention-reasoning/artifacts/method_a_predictor_eval_summary.csv

## Same-model vs. different-model accuracy

Reshapes `summary` (already computed above -- this cell doesn't re-run the
sweep) into one table per task: rows are `MODEL_DATA` (the model whose
samples the predictor was trained/evaluated on), columns are every
`MODEL_TRAIN` (the predictor's backbone). The diagonal -- where
`MODEL_TRAIN == MODEL_DATA` -- is the "same model" (in-distribution) case and
is highlighted; every other cell is "different model" (cross-model).

In [31]:
def style_same_vs_different(df: pd.DataFrame, task: str):
    """Pivot accuracy to a model_data x model_train grid for one task and
    highlight the same-model diagonal. Axis names turn into header labels:
    MODEL_TRAIN sits above the column headers, MODEL_DATA sits beside the
    row index."""
    sub = df[df["task"] == task]
    pivot = sub.pivot_table(index="model_data", columns="model_train", values="accuracy")
    pivot.index.name = "MODEL_DATA"
    pivot.columns.name = "MODEL_TRAIN"

    def highlight_same_model(row):
        return [
            "background-color: #c6f6d5; font-weight: bold" if col == row.name else ""
            for col in pivot.columns
        ]

    styled = (
        pivot.style
        .apply(highlight_same_model, axis=1)
        .format("{:.1%}")
        .set_caption(f"{task} (green = same model)")
    )
    return styled


for _task in summary["task"].unique():
    display(style_same_vs_different(summary, _task))

## Accuracy by difficulty

Reads difficulty straight from the source files already on disk (no
re-generation): `level` for `competition_math` (joined in from the
`eval__baseline__verification-10s__{model_data}.internal.json` file used to
build the eval set, matched on `index`), and `variant` for `countdown`
(already present on each eval record, e.g. `5_operands`).

This uses `detailed_results` populated by the sweep cell above -- if that
dict is empty (e.g. the sweep cell hasn't been re-run since this cell was
added), re-run the sweep cell once to populate it; no model generation needs
to be re-run beyond that.

In [32]:
_level_cache: dict[tuple[str, str], dict[int, str]] = {}


def _competition_math_levels(model_data: str) -> dict[int, str]:
    """index -> ground_truth['level'], read from the internal generations
    file (not the qh_predictions file, which doesn't carry level through)."""
    key = ("competition_math", model_data)
    if key not in _level_cache:
        internal_path = (
            REPO_ROOT
            / "artifacts/competition_math/sft_datasets_verification"
            / f"eval__baseline__verification-10s__{model_data}.internal.json"
        )
        internal_records = load_json(internal_path)
        _level_cache[key] = {
            r["index"]: r["ground_truth"]["level"] for r in internal_records
        }
    return _level_cache[key]


def get_difficulty(record: dict, task: str, model_data: str) -> str:
    """Difficulty label for one eval record."""
    if task == "competition_math":
        return _competition_math_levels(model_data).get(record["index"], "unknown")
    return record.get("variant", "unknown")  # countdown: operand count, e.g. "5_operands"


def accuracy_by_difficulty(task: str, model_data: str, model_train: str) -> pd.DataFrame:
    entry = detailed_results[(task, model_data, model_train)]
    records, predictions = entry["records"], entry["predictions"]

    rows = []
    for record, pred in zip(records, predictions):
        rows.append({
            "difficulty": get_difficulty(record, task, model_data),
            "correct": pred is not None and pred == record["label"],
        })
    df = pd.DataFrame(rows)
    return (
        df.groupby("difficulty")["correct"]
        .agg(accuracy="mean", n="count")
        .reset_index()
        .sort_values("difficulty")
    )


for (task, model_data, model_train) in detailed_results:
    print(f"=== task={task} model_data={model_data} model_train={model_train} ===")
    display(accuracy_by_difficulty(task, model_data, model_train))

=== task=countdown model_data=qwen2.5-3b model_train=qwen2.5-3b ===

   difficulty  accuracy    n
0  4_operands  0.968442  507
1  5_operands  0.778234  487
2  6_operands  0.527668  506

=== task=countdown model_data=qwen2.5-3b model_train=qwen2.5-1.5b ===

   difficulty  accuracy    n
0  4_operands  0.968442  507
1  5_operands  0.778234  487
2  6_operands  0.535573  506

=== task=countdown model_data=qwen3-4b-base model_train=qwen2.5-3b ===

   difficulty  accuracy    n
0  4_operands  0.978304  507
1  5_operands  0.858316  487
2  6_operands  0.598814  506

=== task=countdown model_data=qwen3-4b-base model_train=qwen2.5-1.5b ===

   difficulty  accuracy    n
0  4_operands  0.978304  507
1  5_operands  0.858316  487
2  6_operands  0.620553  506

=== task=competition_math model_data=qwen2.5-3b model_train=qwen2.5-3b ===

  difficulty  accuracy    n
0    Level 1  0.830000  100
1    Level 2  0.791971  274
2    Level 3  0.766382  351
3    Level 4  0.657534  438
4    Level 5  0.678333  600
5    Level ?  1.000000    1

=== task=competition_math model_data=qwen2.5-3b model_train=qwen2.5-1.5b ===

  difficulty  accuracy    n
0    Level 1  0.910000  100
1    Level 2  0.835766  274
2    Level 3  0.806268  351
3    Level 4  0.700913  438
4    Level 5  0.660000  600
5    Level ?  1.000000    1

=== task=competition_math model_data=qwen3-4b-base model_train=qwen2.5-3b ===

  difficulty  accuracy    n
0    Level 1  0.950000  100
1    Level 2  0.941606  274
2    Level 3  0.900285  351
3    Level 4  0.815068  438
4    Level 5  0.673333  600
5    Level ?  1.000000    1

=== task=competition_math model_data=qwen3-4b-base model_train=qwen2.5-1.5b ===

  difficulty  accuracy    n
0    Level 1  0.970000  100
1    Level 2  0.934307  274
2    Level 3  0.903134  351
3    Level 4  0.803653  438
4    Level 5  0.650000  600
5    Level ?  1.000000    1